// @flow

import OsisFormatter from "./osisFormatter";
const osisFormatter = new OsisFormatter();
let currentStyle = "";

const styles = Object.freeze({
    "niv-long": {
        options: {
            ",": "; ",
            "b,c": "; $chapters ",
            "b,v": "; $b ",
            "c,v": "; $c:",
            "v,c": "; $chapters ",
            "v,cv": "; ",
            "v,v": ",",
            $chapters: ["ch.", "chs."],
            $verses: ["v.", "vv."],
            singleChapterFormat: "b",
            "-": "\u2014",
            "b-c": "\u2014$chapters ",
            "b-v": "\u2014$b ",
            "c-v": "\u2014$c:",
            "v-c": "\u2014$chapters ",
            "v-cv": "\u2014",
            "v-v": "\u2013",
            "^c": "$chapters ",
            "b1^v": "$verses ",
            "^v": "$verses ",
        },
        // Many DC book names come from Zondervan's Christian Writer's Manual of Style. https://books.google.com/books?id=qC8XIEFdyYAC&pg=PA21&dq=%22S+of+III+Ch%22&hl=en&sa=X&ved=0ahUKEwiasYy5nbzOAhVJLyYKHYkZBbQQ6AEIHjAA#v=onepage&q=%22S%20of%20III%20Ch%22&f=false
        books: {
            Gen: ["Genesis"],
            Exod: ["Exodus"],
            Lev: ["Leviticus"],
            Num: ["Numbers"],
            Deut: ["Deuteronomy"],
            Josh: ["Joshua"],
            Judg: ["Judges"],
            Ruth: ["Ruth"],
            "1Sam": ["1 Samuel"],
            "2Sam": ["2 Samuel"],
            "1Kgs": ["1 Kings"],
            "2Kgs": ["2 Kings"],
            "1Chr": ["1 Chronicles"],
            "2Chr": ["2 Chronicles"],
            Ezra: ["Ezra"],
            Neh: ["Nehemiah"],
            Esth: ["Esther"],
            Job: ["Job"],
            Ps: ["Psalm", "Psalms"],
            Prov: ["Proverbs"],
            Eccl: ["Ecclesiastes"],
            Song: ["Song of Songs"],
            Isa: ["Isaiah"],
            Jer: ["Jeremiah"],
            Lam: ["Lamentations"],
            Ezek: ["Ezekiel"],
            Dan: ["Daniel"],
            Hos: ["Hosea"],
            Joel: ["Joel"],
            Amos: ["Amos"],
            Obad: ["Obadiah"],
            Jonah: ["Jonah"],
            Mic: ["Micah"],
            Nah: ["Nahum"],
            Hab: ["Habakkuk"],
            Zeph: ["Zephaniah"],
            Hag: ["Haggai"],
            Zech: ["Zechariah"],
            Mal: ["Malachi"],
            Matt: ["Matthew"],
            Mark: ["Mark"],
            Luke: ["Luke"],
            John: ["John"],
            Acts: ["Acts"],
            Rom: ["Romans"],
            "1Cor": ["1 Corinthians"],
            "2Cor": ["2 Corinthians"],
            Gal: ["Galatians"],
            Eph: ["Ephesians"],
            Phil: ["Philippians"],
            Col: ["Colossians"],
            "1Thess": ["1 Thessalonians"],
            "2Thess": ["2 Thessalonians"],
            "1Tim": ["1 Timothy"],
            "2Tim": ["2 Timothy"],
            Titus: ["Titus"],
            Phlm: ["Philemon"],
            Heb: ["Hebrews"],
            Jas: ["James"],
            "1Pet": ["1 Peter"],
            "2Pet": ["2 Peter"],
            "1John": ["1 John"],
            "2John": ["2 John"],
            "3John": ["3 John"],
            Jude: ["Jude"],
            Rev: ["Revelation"],
            Tob: ["Tobit"],
            Jdt: ["Judith"],
            GkEsth: ["Greek Esther"],
            EsthGr: ["Greek Esther"],
            AddEsth: ["Rest of Esther"],
            Wis: ["Wisdom of Solomon"],
            Sir: ["Sirach"],
            Bar: ["Baruch"],
            EpJer: ["Epistle of Jeremiah"],
            DanGr: ["Greek Daniel"],
            SgThree: ["Song of the Three Holy Children"],
            PrAzar: ["Prayer of Azariah"],
            Sus: ["Susanna"],
            Bel: ["Bel and the Dragon"],
            "1Macc": ["1 Maccabees"],
            "2Macc": ["2 Maccabees"],
            "3Macc": ["3 Maccabees"],
            "4Macc": ["4 Maccabees"],
            PrMan: ["Prayer of Manasseh"],
            "1Esd": ["1 Esdras"],
            "2Esd": ["2 Esdras"],
            Ps151: ["Psalm 151"],
            AddPs: ["Psalm 151"],
            // Psalms
            "Ps.$chapters": ["Psalm", "Psalms"],
            // Ranges
            "1Sam-2Sam": ["1\u20142 Samuel"],
            "1Kgs-2Kgs": ["1\u20142 Kings"],
            "1Chr-2Chr": ["1\u20142 Chronicles"],
            "1Cor-2Cor": ["1\u20142 Corinthians"],
            "1Thess-2Thess": ["1\u20142 Thessalonians"],
            "1Tim-2Tim": ["1\u20142 Timothy"],
            "1Pet-2Pet": ["1\u20142 Peter"],
            "1John-2John": ["1\u20142 John"],
            "1John-3John": ["1\u20143 John"],
            "2John-3John": ["2\u20143 John"],
            "1Macc-2Macc": ["1\u20142 Maccabees"],
            "1Macc-3Macc": ["1\u20143 Maccabees"],
            "1Macc-4Macc": ["1\u20144 Maccabees"],
            "2Macc-3Macc": ["2\u20143 Maccabees"],
            "2Macc-4Macc": ["2\u20144 Maccabees"],
            "3Macc-4Macc": ["3\u20144 Maccabees"],
            "1Esd-2Esd": ["1\u20142 Esdras"],
            // Sequences
            "1Sam,2Sam": ["1 and 2 Samuel"],
            "1Kgs,2Kgs": ["1 and 2 Kings"],
            "1Chr,2Chr": ["1 and 2 Chronicles"],
            "1Cor,2Cor": ["1 and 2 Corinthians"],
            "1Thess,2Thess": ["1 and 2 Thessalonians"],
            "1Tim,2Tim": ["1 and 2 Timothy"],
            "1Pet,2Pet": ["1 and 2 Peter"],
            "1John,2John": ["1 and 2 John"],
            "1John,3John": ["1 and 3 John"],
            "2John,3John": ["2 and 3 John"],
            "1Macc,2Macc": ["1 and 2 Maccabees"],
            "1Macc,2Macc,3Macc": ["1, 2, and 3 Maccabees"],
            "1Macc,2Macc,3Macc,4Macc": ["1, 2, 3, and 4 Maccabees"],
            "1Macc,3Macc": ["1 and 3 Maccabees"],
            "1Macc,3Macc,4Macc": ["1, 3, and 4 Maccabees"],
            "1Macc,4Macc": ["1 and 4 Maccabees"],
            "2Macc,3Macc": ["2 and 3 Maccabees"],
            "2Macc,3Macc,4Macc": ["2, 3, and 4 Maccabees"],
            "2Macc,4Macc": ["2 and 4 Maccabees"],
            "3Macc,4Macc": ["3 and 4 Maccabees"],
            "1Esd,2Esd": ["1 and 2 Esdras"],
        },
    },
});

export function formatOsis(osis: string) {
    const style = "niv-long";
    if (style !== currentStyle) {
        setStyle(style);
    }
    return osisFormatter.format(osis);
}

function setStyle(style) {
    if (typeof styles[style] === "undefined") {
        throw `Unknown style: ${style}. Please choose: ${Object.keys(
            styles,
        ).join(", ")}`;
    }
    osisFormatter.setBooks(styles[style].books);
    osisFormatter.setOptions(styles[style].options);
    currentStyle = style;
}
